version: '3'
services:
  discordjs-sandwich-bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./commands:/app/commands
      - ./interactions:/app/interactions
      - ./model:/app/model
      - ./sounds:/app/sounds
      - ./util:/app/util
      - ./config.json:/app/config.json
      - ./googlecloud.json:/app/googlecloud.json
      - ./.env:/app/.env
    restart: always